### ISSUE TITLE
emodnet.github.io/Btrait/ doesn't work?

### ISSUE THREAD

**Issue by LennertSchepers** [EMODnet/Btrait#5]
The github repo mentions the link https://emodnet.github.io/Btrait/ - but this doesn't seem to work.
(in the right upper corner of the repo in the 'about' section)
![image](https://github.com/EMODnet/Btrait/assets/6145889/f59e4d95-f2de-44cc-94ec-ef472982984f)

Cheers
Lennert

**Comment by bart-v** [comment]
I fixed it by building the github pages from branch=main and /docs folder
@salvafern let me know if that is OK or not.
The gh-pages branch is empty: I propose you either configure it properly or we delete it.

**Comment by salvafern** [comment]
fine by me, I deleted gh-pages
